### ISSUE TITLE
"Value not declarable with JSON Schema" on FastAPI /docs

### ISSUE THREAD

**Issue by paolodina** [collerek/ormar#19]
Hi, I'm following [the tutorial]( https://collerek.github.io/ormar/fastapi/) to use ormar with FastAPI  but have an issue on the `/docs` endpoint. My `main.py` contains the code found on the docs and the corresponding database [was created as well](https://collerek.github.io/ormar/models/#database-initialization-migrations) (btw, thanks @collerek for the clarification).

Nevertheless I still get an error on the `/docs` endpoint (every other works fine, after [this change](https://github.com/collerek/ormar/commit/394de2d11cf13b8be5ac06de8d418634d61f6c62#r43603386)).

```
INFO:     127.0.0.1:57856 - "GET /openapi.json HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
.....
ValueError: Value not declarable with JSON Schema, field: name='category' type=Optional[ForeignKey] required=False default=None
```

Full traceback:
```
INFO:     127.0.0.1:57856 - "GET /docs HTTP/1.1" 200 OK
INFO:     127.0.0.1:57856 - "GET /serviceworker.js HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:57856 - "GET /openapi.json HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/paolo/devel/fastapi/.venv/lib/python3.7/site-packages/uvicorn/protocols/http/h11_impl.py", line 389, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/paolo/devel/fastapi/.venv/lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/home/paolo/devel/fastapi/.venv/lib/python3.7/site-packages/fastapi/applications.py", line 179, in __call__
    await super().__call__(scope, receive, send)
  File "/home/paolo/devel/fastapi/.venv/lib/python3.7/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/paolo/devel/fastapi/.venv/lib/python3.7/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/paolo/devel/fastapi/.venv/lib/python3.7/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/paolo/devel/fastapi/.venv/lib/python3.7/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/paolo/devel/fastapi/.venv/lib/python3.7/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/paolo/devel/fastapi/.venv/lib/python3.7/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/home/paolo/devel/fastapi/.venv/lib/python3.7/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/home/paolo/devel/fastapi/.venv/lib/python3.7/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/home/paolo/devel/fastapi/.venv/lib/python3.7/site-packages/fastapi/applications.py", line 128, in openapi
    return JSONResponse(self.openapi())
  File "/home/paolo/devel/fastapi/.venv/lib/python3.7/site-packages/fastapi/applications.py", line 113, in openapi
    servers=self.servers,
  File "/home/paolo/devel/fastapi/.venv/lib/python3.7/site-packages/fastapi/openapi/utils.py", line 344, in get_openapi
    flat_models=flat_models, model_name_map=model_name_map  # type: ignore
  File "/home/paolo/devel/fastapi/.venv/lib/python3.7/site-packages/fastapi/utils.py", line 25, in get_model_definitions
    model, model_name_map=model_name_map, ref_prefix=REF_PREFIX  # type: ignore
  File "/home/paolo/devel/fastapi/.venv/lib/python3.7/site-packages/pydantic/schema.py", line 468, in model_process_schema
    model, by_alias=by_alias, model_name_map=model_name_map, ref_prefix=ref_prefix, known_models=known_models
  File "/home/paolo/devel/fastapi/.venv/lib/python3.7/site-packages/pydantic/schema.py", line 504, in model_type_schema
    f, by_alias=by_alias, model_name_map=model_name_map, ref_prefix=ref_prefix, known_models=known_models
  File "/home/paolo/devel/fastapi/.venv/lib/python3.7/site-packages/pydantic/schema.py", line 198, in field_schema
    known_models=known_models or set(),
  File "/home/paolo/devel/fastapi/.venv/lib/python3.7/site-packages/pydantic/schema.py", line 425, in field_type_schema
    known_models=known_models,
  File "/home/paolo/devel/fastapi/.venv/lib/python3.7/site-packages/pydantic/schema.py", line 740, in field_singleton_schema
    raise ValueError(f'Value not declarable with JSON Schema, field: {field}')
ValueError: Value not declarable with JSON Schema, field: name='category' type=Optional[ForeignKey] required=False default=None
```

```
$ pip freeze

aiosqlite==0.15.0
asyncpg==0.21.0
click==7.1.2
databases==0.4.0
fastapi==0.61.1
flake8==3.8.4
h11==0.11.0
importlib-metadata==2.0.0
mccabe==0.6.1
ormar==0.3.8
pkg-resources==0.0.0
psycopg2==2.8.6
pycodestyle==2.6.0
pydantic==1.6.1
pyflakes==2.2.0
SQLAlchemy==1.3.20
starlette==0.13.6
typing-extensions==3.7.4.3
uvicorn==0.12.2
zipp==3.4.0
```

Any help greatly appreciated.

**Comment by collerek** [comment]
Hi, There was a bug in relation of schema generation for nested models.
Should be fixed with #21.

Please update ormar to latest version (0.3.9), and give it a try.
