### ISSUE TITLE
update_or_create raising NoMatch()

### ISSUE THREAD

**Issue by muqshots** [collerek/ormar#269]
**Describe the bug**
method update_or_create raises NoMatch() instead of creating object

**To Reproduce**
Models defined as follows
```
class Movie(ormar.Model):
    class Meta(BaseMeta):
        tablename = 'movies'

    tmdb_id: int = ormar.Integer(nullable=False, primary_key=True)
    path: str = ormar.String(max_length=255)
```

route as follows
```
@router.post('/radarr')
async def add_movie(movie_to_add: AddMovieSchema):
    tmdb_id = movie_to_add.remoteMovie.tmdbId
    folder = movie_to_add.movie.folderPath.lstrip('/data/media/movies/merge/')
    filename = movie_to_add.movieFile.relativePath
    moviepath = os.path.join(folder, filename)
    movie = await Movie.objects.update_or_create(tmdb_id=tmdb_id, path=moviepath)
    return {}
```

(Note: this should be a complete and concise piece of code that allows reproduction of an issue)

**Expected behavior**
If the pk tmdb_id exists, it will update the path column
If the pk tmdb_id does not exist it will create the row

**Screenshots**

**Versions (please complete the following information):**
 - Database backend used (mysql/sqlite/postgress) - sqlite
 - Python version - 3.9.1
 - `ormar` version - 0.10.14
 - `pydantic` version - 1.8.2
 - if applicable `fastapi` version - 0.66.0

**Additional context**
error traceback 
```
INFO:     127.0.0.1:63368 - "POST /radarr HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 371, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 59, in __call__      
    return await self.app(scope, receive, send)
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\fastapi\applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
    raise exc from None
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    raise exc from None
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\starlette\exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\starlette\routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\starlette\routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\starlette\routing.py", line 52, in app
    response = await func(request)
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\fastapi\routing.py", line 216, in app
    raw_response = await run_endpoint_function(
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\fastapi\routing.py", line 149, in run_endpoint_function
    return await dependant.call(**values)
  File ".\app\routers\api\mediarr.py", line 20, in add_movie
    movie = await Movie.objects.update_or_create(tmdb_id=tmdb_id, path=path)
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\ormar\queryset\queryset.py", line 987, in update_or_create
    model = await self.get(pk=kwargs[pk_name])
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\ormar\queryset\queryset.py", line 929, in get
    return await self.filter(*args, **kwargs).get()
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\ormar\queryset\queryset.py", line 949, in get
    self.check_single_result_rows_count(processed_rows)
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\ormar\queryset\queryset.py", line 225, in check_single_result_rows_count
    raise NoMatch()
ormar.exceptions.NoMatch
```

**Comment by collerek** [comment]
For now this `update_or_create` is just a proxy to `update` or `create`. 

The method is chosen based on the primary key presence. If the pk is set then update, if not then create. Since you probably provide the value of id it tries to update this record, hence the exception.

It was created as a shortcut method that didn't check the presence of the record in db to increase the speed of execution (you need a second query to check for the record). 

That should definitely be changed/improved, thanks for pointing it out.

**Comment by muqshots** [comment]
Ah thanks for the explanation, would this be the correct way to do it now?
```
movie = Movie.objects.filter(tmdb_id=tmdb_id).get_or_none()
if movie:
    await movie.update(path=path)
else:
    movie = await Movie(tmdb_id=tmdb_id, path=path).save()
```

**Comment by collerek** [comment]
Yep, definitely one of the ways.

You can also pass `kwargs` to `get_or_none` that way you can skip `filter`.

You can also use normal `get` (also accepts kwargs) and catch the `NoMatch` exception and create in catch block. 

But it's all about preference, from functionality perspective it's all the same.

**Comment by muqshots** [comment]
Alright thanks!, I'll close the issue now,
Perhaps the documentation can be updated to clarify this a bit.

**Comment by pawamoy** [comment]
Bumped into this as well. I was wondering anyway how ormar could know which kwargs to use to get the row and which one to use to update it / create it. Now I know that it always tries to create without an id/pk,

**Comment by collerek** [comment]
@pawamoy - yeah I need to update the docs -> will include this in the next release.

And exactly it has to work this way as otherwise all kwargs would be used to select an object 
- so there is nothing to update (if one is found using all kwargs it's already the same) 
- or would result in an integrity error if it's not found but the pk is duplicated (so instead of update would try to create a new one with the same pk).

So it's actually using all kwargs without the primary key to update the object and determines create/update based on the primary key presence.
