### ISSUE TITLE
Many to many Relation error.

### ISSUE THREAD

**Issue by luisjimenez6245** [collerek/ormar#30]
Hi, im getting an error while trying to use Many to Many Relation.  

`Process SpawnProcess-1:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/luis/Documents/GitHub/agenda-api/venv/lib/python3.9/site-packages/uvicorn/subprocess.py", line 62, in subprocess_started
    target(sockets=sockets)
  File "/Users/luis/Documents/GitHub/agenda-api/venv/lib/python3.9/site-packages/uvicorn/main.py", line 390, in run
    loop.run_until_complete(self.serve(sockets=sockets))
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "/Users/luis/Documents/GitHub/agenda-api/venv/lib/python3.9/site-packages/uvicorn/main.py", line 397, in serve
    config.load()
  File "/Users/luis/Documents/GitHub/agenda-api/venv/lib/python3.9/site-packages/uvicorn/config.py", line 278, in load
    self.loaded_app = import_from_string(self.app)
  File "/Users/luis/Documents/GitHub/agenda-api/venv/lib/python3.9/site-packages/uvicorn/importer.py", line 20, in import_from_string
    module = importlib.import_module(module_str)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "./main.py", line 5, in <module>
    from routes.utils import origins, paths, methods
  File "./routes/__init__.py", line 1, in <module>
    from .models import models_routes
  File "./routes/models/__init__.py", line 1, in <module>
    from .Users import router as user_router
  File "./routes/models/Users.py", line 3, in <module>
    from models import User
  File "./models/__init__.py", line 1, in <module>
    from .User import User
  File "./models/User.py", line 7, in <module>
    class User(orm.Model):
  File "/Users/luis/Documents/GitHub/agenda-api/venv/lib/python3.9/site-packages/ormar/models/metaclass.py", line 327, in __new__
    expand_reverse_relationships(new_model)
  File "/Users/luis/Documents/GitHub/agenda-api/venv/lib/python3.9/site-packages/ormar/models/metaclass.py", line 72, in expand_reverse_relationships
    register_reverse_model_fields(
  File "/Users/luis/Documents/GitHub/agenda-api/venv/lib/python3.9/site-packages/ormar/models/metaclass.py", line 88, in register_reverse_model_fields
    adjust_through_many_to_many_model(model, child, model_field)
  File "/Users/luis/Documents/GitHub/agenda-api/venv/lib/python3.9/site-packages/ormar/models/metaclass.py", line 105, in adjust_through_many_to_many_model
    create_and_append_m2m_fk(model, model_field)
  File "/Users/luis/Documents/GitHub/agenda-api/venv/lib/python3.9/site-packages/ormar/models/metaclass.py", line 137, in create_and_append_m2m_fk
    model_field.through.Meta.table.append_column(column)
AttributeError: 'str' object has no attribute 'append_column'`

Here are my models:

`
class User(orm.Model):

    id: int = orm.Integer(name="user_id", primary_key=True)
    username: str = orm.String(max_length=50, unique=False)
    password: str = orm.Text()
    user_type: str = orm.String(max_length=100)
    contact_info: Union[Contact, Dict] = orm.ForeignKey(Contact)
    contacts: Optional[Union[Contact, List[Contact] ]]  = orm.ManyToMany(Contact, through = UserContacts)
    
    class Meta(MainMeta):
        table_name = "users"
`

`
class Contact(orm.Model):

    id: int = orm.Integer(name="contact_id", primary_key=True)
    name: str = orm.String(max_length=200, server_default="")

    class Meta(MainMeta):
        table_name = "contacts"

`

`
class UserContacts(orm.Model):
    id:int  = orm.Integer(name = "rel_user_contact_id", primary_key = True)
    class Meta(MainMeta):
        table = "rel_user_contacts"
`

**Comment by luisjimenez6245** [comment]
It was my error, I got cofuse with the naming. :( sorry
