### ISSUE TITLE
Swager pydantic.error_wrappers.ValidationError when required=True on ormar.String()

### ISSUE THREAD

**Issue by alexwolf22** [collerek/ormar#871]
**Describe the bug**

I have a text field in my Ormar model which is required. I am setting this as the input and response model in my fast API endpoint like below.

```python
class Todo(ormar.Model):
    """
    DB Model Representing a Todo
    """
    class Meta:
        database = database
        metadata = metadata

    id: int = ormar.Integer(primary_key=True)
    text: str = ormar.String(max_length=100, nullable=False, required=True)
    completed: bool = ormar.Boolean(default=False)
    created_at: datetime.datetime = ormar.DateTime(default=datetime.datetime.now())
    completed_at: Optional[datetime.datetime] = ormar.DateTime(nullable=True)

@app.get('/todo', response_model=Todo)
def create_todo(todo: Todo) -> Todo:
    """
    Create a Todo
    """
    return todo
```

I get the following error when trying to open swagger. When I removed the`required=True` part of my ORMAR model swagger loads with no error

```
backend_1  | INFO:     Will watch for changes in these directories: ['/opt/project']
backend_1  | INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
backend_1  | INFO:     Started reloader process [1] using StatReload
backend_1  | INFO:     Started server process [11]
backend_1  | INFO:     Waiting for application startup.
backend_1  | INFO:     Application startup complete.
backend_1  | INFO:     172.18.0.1:55184 - "GET /docs HTTP/1.1" 200 OK
backend_1  | INFO:     172.18.0.1:55184 - "GET /openapi.json HTTP/1.1" 500 Internal Server Error
backend_1  | ERROR:    Exception in ASGI application
backend_1  | Traceback (most recent call last):
backend_1  |   File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 404, in run_asgi
backend_1  |     result = await app(  # type: ignore[func-returns-value]
backend_1  |   File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
backend_1  |     return await self.app(scope, receive, send)
backend_1  |   File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 199, in __call__
backend_1  |     await super().__call__(scope, receive, send)
backend_1  |   File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 112, in __call__
backend_1  |     await self.middleware_stack(scope, receive, send)
backend_1  |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
backend_1  |     raise exc from None
backend_1  |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
backend_1  |     await self.app(scope, receive, _send)
backend_1  |   File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
backend_1  |     raise exc from None
backend_1  |   File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
backend_1  |     await self.app(scope, receive, sender)
backend_1  |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 580, in __call__
backend_1  |     await route.handle(scope, receive, send)
backend_1  |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 241, in handle
backend_1  |     await self.app(scope, receive, send)
backend_1  |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 52, in app
backend_1  |     response = await func(request)
backend_1  |   File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 152, in openapi
backend_1  |     return JSONResponse(self.openapi())
backend_1  |   File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 130, in openapi
backend_1  |     self.openapi_schema = get_openapi(
backend_1  |   File "/usr/local/lib/python3.9/site-packages/fastapi/openapi/utils.py", line 386, in get_openapi
backend_1  |     return jsonable_encoder(OpenAPI(**output), by_alias=True, exclude_none=True)  # type: ignore
backend_1  |   File "pydantic/main.py", line 391, in pydantic.main.BaseModel.__init__
backend_1  | pydantic.error_wrappers.ValidationError: 2 validation errors for OpenAPI
backend_1  | components -> schemas -> Todo -> properties -> text -> required
backend_1  |   value is not a valid list (type=type_error.list)
backend_1  | components -> schemas -> Todo -> $ref
backend_1  |   field required (type=value_error.missing)
```

<img width="1558" alt="image" src="https://user-images.githubusercontent.com/17020909/194670017-1ebdfadc-4f48-4f1e-b36a-cffe33fa294b.png">

**Versions (please complete the following information):**
 - Database backend used (mysql/sqlite/postgress)
 - Python version
 - `ormar` version `ormar[postgresql]==0.10.8`
 - `pydantic` version `1.8`
 - if applicable `fastapi` version `0.65.0`

**Comment by collerek** [comment]
There is no `required` param in ormar, you have `nullable` (and `sql_nullable`), hence the error.
